import os
import re
import pyodbc
from dotenv import load_dotenv
from fastmcp import FastMCP
import sys
load_dotenv()

mcp = FastMCP("Flight Data Agent")

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.append(BASE_DIR)

# ---------------------------------------
# Schema Context
# ---------------------------------------
SCHEMA = """
Table: flights_gold
Columns:
- icao24 (string) — unique aircraft identifier
- callsign (string) — flight call sign
- origin_country (string) — country of origin
- latitude (float) — current latitude
- longitude (float) — current longitude
- baro_altitude (float) — barometric altitude in meters
- velocity (float) — speed in m/s
- on_ground (boolean) — true if aircraft is on ground
- true_track (float) — direction in degrees
- vertical_rate (float) — climbing/descending rate in m/s
- time_position (string) — last position update time
- last_contact (string) — last contact time
- status (string) — ACTIVE, INACTIVE, LANDED
- status_reason (string) — in_air, on_ground_flag, last_contact_exceeded_3hrs
- source_type (string) — ADS-B, ASTERIX, MLAT, FLARM, UNKNOWN
- ingestion_time (string) — when record was ingested

Rules:
- EXPIRED records are filtered out — not present in this table
- Status values: ACTIVE, INACTIVE, LANDED only
- Use SELECT only — no INSERT, UPDATE, DELETE
"""

# ---------------------------------------
# Synapse Connection
# ---------------------------------------
def get_connection():
    server   = os.environ.get("SYNAPSE_SERVER")
    database = os.environ.get("SYNAPSE_DB")
    username = os.environ.get("SYNAPSE_USER")
    password = os.environ.get("SYNAPSE_PASSWORD")

    conn = pyodbc.connect(
        f"DRIVER={{ODBC Driver 17 for SQL Server}};"
        f"SERVER={server};"
        f"DATABASE={database};"
        f"UID={username};"
        f"PWD={password}"
    )
    return conn


# ---------------------------------------
# Tool 1 — Get Schema
# ---------------------------------------
@mcp.tool()
def get_schema() -> str:
    """Returns Gold layer flight data schema for LLM context"""
    return SCHEMA


# ---------------------------------------
# Tool 2 — Validate and Execute Query
# ---------------------------------------
@mcp.tool()
def validate_and_execute_query(sql: str) -> dict:
    """Validates SQL generated by LLM and executes on Synapse"""

    sql_clean = sql.strip().upper()

    # Only SELECT allowed
    if not sql_clean.startswith("SELECT"):
        return {
            "success": False,
            "error": "Only SELECT queries allowed."
        }

    # Blocked keywords
    blocked = [
        "DELETE", "DROP", "UPDATE", "INSERT",
        "TRUNCATE", "ALTER", "CREATE", "EXEC", "EXECUTE"
    ]
    for keyword in blocked:
        if keyword in sql_clean:
            return {
                "success": False,
                "error": f"Blocked keyword detected: {keyword}"
            }

    # Injection patterns
    patterns = [r"--", r"/\*", r";\s*\w", r"xp_", r"UNION\s+SELECT"]
    for pattern in patterns:
        if re.search(pattern, sql_clean):
            return {
                "success": False,
                "error": "Suspicious SQL pattern detected."
            }

    # Execute
    try:
        conn = get_connection()
        cursor = conn.cursor()
        cursor.execute(sql)
        columns = [col[0] for col in cursor.description]
        rows = [dict(zip(columns, row)) for row in cursor.fetchall()]
        return {
            "success": True,
            "result": rows
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"Query execution failed: {str(e)}"
        }


# ---------------------------------------
# Run MCP Server
# ---------------------------------------
if __name__ == "__main__":
    mcp.run()